export const SET_MINUTES_FOCUS = "SET_MINUTES_FOCUS";
export const SET_MINUTES_BREAK = "SET_MINUTES_BREAK";
export const SET_MINUTES_BREAK_LARGE = "SET_MINUTES_BREAK_LARGE";
export const SET_LONG_BREAK_INTERVAL = "SET_LONG_BREAK_INTERVAL";
export const SET_INTERVAL_GOAL = "SET_INTERVAL_GOAL";
export const SET_CURRENT_INTERVAL = "SET_CURRENT_INTERVAL";